Set invert_colors to fix build
esphome/firmware pull request #267
Opened 2024-09-21 18:52 UTC by deisterhold

2024-09-25 18:55 UTC, LiamAkkerman commented
I have also run into this issue since https://github.com/esphome/esphome/pull/7292 was merged. Just as a note, this PR only addresses the ESP32-S3-BOX yaml, not the ESP32-S3-BOX-3 or ESP32-S3-BOX-Lite yamls.

2024-09-25 19:05 UTC, deisterhold commented
Updated to include the other two variants as well.

2024-09-27 17:23 UTC, LiamAkkerman commented
Using my ESP32-S3-BOX-3, I can confirm that making the following change allowed me to build again and the voice assistant functions
```
packages:
  esphome.voice-assistant: github://deisterhold/firmware/voice-assistant/esp32-s3-box-3.yaml@patch-1
  # esphome.voice-assistant: github://esphome/firmware/voice-assistant/esp32-s3-box-3.yaml@main
```

2024-09-29 22:25 UTC, jesserockz requested changes

2024-09-29 22:25 UTC, jesserockz commented on voice-assistant/esp32-s3-box-lite.yaml
> +    invert_colors: false
Please don't add changes to a PR if you have not tested it
```suggestion
    invert_colors: true
```

2024-09-30 01:23 UTC, merged