Add switch for listen light
esphome/firmware pull request #67
Opened 2023-10-17 09:29 UTC by TheFes

Added switch to enable or disable the listen light, could be useful if you have the device in the bedroom for example, and want to turn off the light at night.
(or if you just don't want the light at all).

2023-10-17 09:40 UTC, jesserockz requested changes

2023-10-17 09:40 UTC, jesserockz commented on voice-assistant/m5stack-atom-echo.yaml
> +    restore_mode: RESTORE_DEFAULT_ON
```suggestion
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
```

2023-10-17 10:44 UTC, TheFes commented
@jesserockz I applied the requested change, but somehow it keeps showing `Changes requested`

2023-10-19 07:08 UTC, jesserockz approved these changes

2023-10-19 07:08 UTC, merged